hometask 14
foxoter/mesto-server pull request #4
Opened 2020-11-20 14:59 UTC by foxoter

Features implemented: 

- user authorisation,
- routes protection

2020-11-20 22:16 UTC, ramiltk53 requested changes
**Здравствуйте!** Очень хорошая работа! Соблюдены почти все пункты, но есть несколько мест, которые надо бы исправить. Они указаны в файлах.

2020-11-20 22:16 UTC, ramiltk53 commented on controllers/users.js
> +              .send({ message: 'Some data is invalid' });
**Надо исправить:**
"Some data is invalid" не очень хорошее описание для ошибки, ведь у нас в err приходит что именно не прошло валидацию, можно сразу сообщить, чтобы пользователь не искал сам

2020-11-20 22:16 UTC, ramiltk53 commented on models/user.js
> +  password: {
**Можно лучше:**
В методе `createUser` вы проверяете с помощью регулярного выражения размер пароля, есть ли в нём 8 символов, можно добавить эту проверку сюда, с помощью `minlength`

2020-11-21 10:58 UTC, foxoter commented
Спасибо за ревью!

Внёс правки.

2020-11-21 16:04 UTC, ramiltk53 requested changes
**Здравствуйте!** Спасибо за проделанные изменения! Очень хорошая работа

Осталась лишь 1 небольшая ошибка. В error , который возвращается с Mongoose схемы пишется какое именно поле не прошло валидацию

2020-11-21 20:07 UTC, foxoter commented
Спасибо. Исправил.

2020-11-21 21:24 UTC, ramiltk53 approved these changes
**Здравствуйте!**

Спасибо за проделанную работу и поправки. Работа принял. 

Удачи в дальнейшем ! 👍

2020-11-22 04:50 UTC, merged